spring:
  datasource:
    hikari:
      maximum-pool-size: 50
    username: admin
    password: admin
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver

  flyway:
    enabled: true
    validate-on-migrate: true

  jpa:
    open-in-view: true
